### ISSUE TITLE
list servers using this mod

### ISSUE THREAD

**Issue by Vincent14** [GitHub-TC/EmpyrionPassenger#2]
My comment could apply to all your mods at the end, as a player I have not found a way to list public servers using your awesome mods.

I would join easily servers using this mod in particular but some other are also interesting IMO :)

**Comment by GitHub-TC** [comment]
The only possibility is that the server operator includes this in its description. Unfortunately, Eleon does not offer the possibility of automatically specifying this for a server.

But you can post these ideas in the forum and maybe Eleon will implement them.
